import { Router } from "express";
import * as authcontroller from "../controllers/auth.controller.js";
import { authenticate, requireAdmin } from "../middlewares/auth.middleware.js";
const authRouter = Router();

authRouter.post("/register", authcontroller.register);
authRouter.post("/login", authcontroller.login);
authRouter.get("/get-me", authenticate, authcontroller.getMe);
authRouter.get("/refresh", authcontroller.refresh);
authRouter.post("/logout", authcontroller.logout);
authRouter.post("/logout-all", authcontroller.logoutAll);
authRouter.post("/verify-email", authcontroller.verifyEmail);
authRouter.post("/resend-otp", authcontroller.resendOTP);
authRouter.post("/resend-otp", authcontroller.resendOTP);
authRouter.get("/admin/agents", authenticate, requireAdmin, authcontroller.getAgents);
authRouter.post("/admin/agents", authenticate, requireAdmin, authcontroller.createAgent);
authRouter.patch("/admin/agents/:agentId/status", authenticate, requireAdmin, authcontroller.updateAgentStatus);
authRouter.get("/admin/customers", authenticate, requireAdmin, authcontroller.getCustomers);
authRouter.get("/admin/customers/:customerId", authenticate, requireAdmin, authcontroller.getCustomerById);
authRouter.get("/admin/analytics", authenticate, requireAdmin, authcontroller.getAnalytics);
authRouter.get("/admin/settings", authenticate, requireAdmin, authcontroller.getSettings);
authRouter.put("/admin/settings", authenticate, requireAdmin, authcontroller.updateSettings);
authRouter.put("/admin/profile", authenticate, requireAdmin, authcontroller.updateProfile);
export default authRouter;
